[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "piximi-contour-interpolation"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
interpolate-1 = "python ./interpolate.py ./public/ExternalInterpolation.nrrd ./public/ExternalInterpolationOutput.nrrd"
build-volume-1 = "python build_volume.py ./ExternalInterpolation ./public/ExternalInterpolation.nrrd"

[dependencies]
python = ">=3.12.5,<4"
pnpm = ">=9.9.0,<10"
rich = ">=13.7.1,<14"

[pypi-dependencies]
itkwasm-morphological-contour-interpolation = ">=1.1.0, <2"
itkwasm-image-io = ">=1.3.0, <2"
