[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "piximi-contour-interpolation"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
interpolate = "python ./interpolate.py"

[dependencies]
python = ">=3.12.5,<4"
pnpm = ">=9.9.0,<10"

[pypi-dependencies]
itkwasm-morphological-contour-interpolation = ">=1.1.0, <2"
itkwasm-image-io = ">=1.3.0, <2"
